/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces_.$workspaceId'
import { Route as WorkspacesWorkspaceIdWebhooksRouteImport } from './routes/workspaces_.$workspaceId_.webhooks'
import { Route as WorkspacesWorkspaceIdSessionsRouteImport } from './routes/workspaces_.$workspaceId_.sessions'
import { Route as WorkspacesWorkspaceIdPeersRouteImport } from './routes/workspaces_.$workspaceId_.peers'
import { Route as WorkspacesWorkspaceIdConclusionsRouteImport } from './routes/workspaces_.$workspaceId_.conclusions'
import { Route as WorkspacesWorkspaceIdSessionsSessionIdRouteImport } from './routes/workspaces_.$workspaceId_.sessions_.$sessionId'
import { Route as WorkspacesWorkspaceIdPeersPeerIdRouteImport } from './routes/workspaces_.$workspaceId_.peers_.$peerId'
import { Route as WorkspacesWorkspaceIdPeersPeerIdChatRouteImport } from './routes/workspaces_.$workspaceId_.peers_.$peerId_.chat'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/workspaces_/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdWebhooksRoute =
  WorkspacesWorkspaceIdWebhooksRouteImport.update({
    id: '/workspaces_/$workspaceId_/webhooks',
    path: '/workspaces/$workspaceId/webhooks',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdSessionsRoute =
  WorkspacesWorkspaceIdSessionsRouteImport.update({
    id: '/workspaces_/$workspaceId_/sessions',
    path: '/workspaces/$workspaceId/sessions',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdPeersRoute =
  WorkspacesWorkspaceIdPeersRouteImport.update({
    id: '/workspaces_/$workspaceId_/peers',
    path: '/workspaces/$workspaceId/peers',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdConclusionsRoute =
  WorkspacesWorkspaceIdConclusionsRouteImport.update({
    id: '/workspaces_/$workspaceId_/conclusions',
    path: '/workspaces/$workspaceId/conclusions',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdSessionsSessionIdRoute =
  WorkspacesWorkspaceIdSessionsSessionIdRouteImport.update({
    id: '/workspaces_/$workspaceId_/sessions_/$sessionId',
    path: '/workspaces/$workspaceId/sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdPeersPeerIdRoute =
  WorkspacesWorkspaceIdPeersPeerIdRouteImport.update({
    id: '/workspaces_/$workspaceId_/peers_/$peerId',
    path: '/workspaces/$workspaceId/peers/$peerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacesWorkspaceIdPeersPeerIdChatRoute =
  WorkspacesWorkspaceIdPeersPeerIdChatRouteImport.update({
    id: '/workspaces_/$workspaceId_/peers_/$peerId_/chat',
    path: '/workspaces/$workspaceId/peers/$peerId/chat',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/settings': typeof SettingsRoute
  '/workspaces': typeof WorkspacesRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/workspaces/$workspaceId/conclusions': typeof WorkspacesWorkspaceIdConclusionsRoute
  '/workspaces/$workspaceId/peers': typeof WorkspacesWorkspaceIdPeersRoute
  '/workspaces/$workspaceId/sessions': typeof WorkspacesWorkspaceIdSessionsRoute
  '/workspaces/$workspaceId/webhooks': typeof WorkspacesWorkspaceIdWebhooksRoute
  '/workspaces/$workspaceId/peers/$peerId': typeof WorkspacesWorkspaceIdPeersPeerIdRoute
  '/workspaces/$workspaceId/sessions/$sessionId': typeof WorkspacesWorkspaceIdSessionsSessionIdRoute
  '/workspaces/$workspaceId/peers/$peerId/chat': typeof WorkspacesWorkspaceIdPeersPeerIdChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/settings': typeof SettingsRoute
  '/workspaces': typeof WorkspacesRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/workspaces/$workspaceId/conclusions': typeof WorkspacesWorkspaceIdConclusionsRoute
  '/workspaces/$workspaceId/peers': typeof WorkspacesWorkspaceIdPeersRoute
  '/workspaces/$workspaceId/sessions': typeof WorkspacesWorkspaceIdSessionsRoute
  '/workspaces/$workspaceId/webhooks': typeof WorkspacesWorkspaceIdWebhooksRoute
  '/workspaces/$workspaceId/peers/$peerId': typeof WorkspacesWorkspaceIdPeersPeerIdRoute
  '/workspaces/$workspaceId/sessions/$sessionId': typeof WorkspacesWorkspaceIdSessionsSessionIdRoute
  '/workspaces/$workspaceId/peers/$peerId/chat': typeof WorkspacesWorkspaceIdPeersPeerIdChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/settings': typeof SettingsRoute
  '/workspaces': typeof WorkspacesRoute
  '/workspaces_/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/workspaces_/$workspaceId_/conclusions': typeof WorkspacesWorkspaceIdConclusionsRoute
  '/workspaces_/$workspaceId_/peers': typeof WorkspacesWorkspaceIdPeersRoute
  '/workspaces_/$workspaceId_/sessions': typeof WorkspacesWorkspaceIdSessionsRoute
  '/workspaces_/$workspaceId_/webhooks': typeof WorkspacesWorkspaceIdWebhooksRoute
  '/workspaces_/$workspaceId_/peers_/$peerId': typeof WorkspacesWorkspaceIdPeersPeerIdRoute
  '/workspaces_/$workspaceId_/sessions_/$sessionId': typeof WorkspacesWorkspaceIdSessionsSessionIdRoute
  '/workspaces_/$workspaceId_/peers_/$peerId_/chat': typeof WorkspacesWorkspaceIdPeersPeerIdChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/settings'
    | '/workspaces'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/conclusions'
    | '/workspaces/$workspaceId/peers'
    | '/workspaces/$workspaceId/sessions'
    | '/workspaces/$workspaceId/webhooks'
    | '/workspaces/$workspaceId/peers/$peerId'
    | '/workspaces/$workspaceId/sessions/$sessionId'
    | '/workspaces/$workspaceId/peers/$peerId/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/settings'
    | '/workspaces'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/conclusions'
    | '/workspaces/$workspaceId/peers'
    | '/workspaces/$workspaceId/sessions'
    | '/workspaces/$workspaceId/webhooks'
    | '/workspaces/$workspaceId/peers/$peerId'
    | '/workspaces/$workspaceId/sessions/$sessionId'
    | '/workspaces/$workspaceId/peers/$peerId/chat'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/settings'
    | '/workspaces'
    | '/workspaces_/$workspaceId'
    | '/workspaces_/$workspaceId_/conclusions'
    | '/workspaces_/$workspaceId_/peers'
    | '/workspaces_/$workspaceId_/sessions'
    | '/workspaces_/$workspaceId_/webhooks'
    | '/workspaces_/$workspaceId_/peers_/$peerId'
    | '/workspaces_/$workspaceId_/sessions_/$sessionId'
    | '/workspaces_/$workspaceId_/peers_/$peerId_/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  SettingsRoute: typeof SettingsRoute
  WorkspacesRoute: typeof WorkspacesRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRoute
  WorkspacesWorkspaceIdConclusionsRoute: typeof WorkspacesWorkspaceIdConclusionsRoute
  WorkspacesWorkspaceIdPeersRoute: typeof WorkspacesWorkspaceIdPeersRoute
  WorkspacesWorkspaceIdSessionsRoute: typeof WorkspacesWorkspaceIdSessionsRoute
  WorkspacesWorkspaceIdWebhooksRoute: typeof WorkspacesWorkspaceIdWebhooksRoute
  WorkspacesWorkspaceIdPeersPeerIdRoute: typeof WorkspacesWorkspaceIdPeersPeerIdRoute
  WorkspacesWorkspaceIdSessionsSessionIdRoute: typeof WorkspacesWorkspaceIdSessionsSessionIdRoute
  WorkspacesWorkspaceIdPeersPeerIdChatRoute: typeof WorkspacesWorkspaceIdPeersPeerIdChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId': {
      id: '/workspaces_/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/webhooks': {
      id: '/workspaces_/$workspaceId_/webhooks'
      path: '/workspaces/$workspaceId/webhooks'
      fullPath: '/workspaces/$workspaceId/webhooks'
      preLoaderRoute: typeof WorkspacesWorkspaceIdWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/sessions': {
      id: '/workspaces_/$workspaceId_/sessions'
      path: '/workspaces/$workspaceId/sessions'
      fullPath: '/workspaces/$workspaceId/sessions'
      preLoaderRoute: typeof WorkspacesWorkspaceIdSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/peers': {
      id: '/workspaces_/$workspaceId_/peers'
      path: '/workspaces/$workspaceId/peers'
      fullPath: '/workspaces/$workspaceId/peers'
      preLoaderRoute: typeof WorkspacesWorkspaceIdPeersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/conclusions': {
      id: '/workspaces_/$workspaceId_/conclusions'
      path: '/workspaces/$workspaceId/conclusions'
      fullPath: '/workspaces/$workspaceId/conclusions'
      preLoaderRoute: typeof WorkspacesWorkspaceIdConclusionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/sessions_/$sessionId': {
      id: '/workspaces_/$workspaceId_/sessions_/$sessionId'
      path: '/workspaces/$workspaceId/sessions/$sessionId'
      fullPath: '/workspaces/$workspaceId/sessions/$sessionId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/peers_/$peerId': {
      id: '/workspaces_/$workspaceId_/peers_/$peerId'
      path: '/workspaces/$workspaceId/peers/$peerId'
      fullPath: '/workspaces/$workspaceId/peers/$peerId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdPeersPeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces_/$workspaceId_/peers_/$peerId_/chat': {
      id: '/workspaces_/$workspaceId_/peers_/$peerId_/chat'
      path: '/workspaces/$workspaceId/peers/$peerId/chat'
      fullPath: '/workspaces/$workspaceId/peers/$peerId/chat'
      preLoaderRoute: typeof WorkspacesWorkspaceIdPeersPeerIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  SettingsRoute: SettingsRoute,
  WorkspacesRoute: WorkspacesRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRoute,
  WorkspacesWorkspaceIdConclusionsRoute: WorkspacesWorkspaceIdConclusionsRoute,
  WorkspacesWorkspaceIdPeersRoute: WorkspacesWorkspaceIdPeersRoute,
  WorkspacesWorkspaceIdSessionsRoute: WorkspacesWorkspaceIdSessionsRoute,
  WorkspacesWorkspaceIdWebhooksRoute: WorkspacesWorkspaceIdWebhooksRoute,
  WorkspacesWorkspaceIdPeersPeerIdRoute: WorkspacesWorkspaceIdPeersPeerIdRoute,
  WorkspacesWorkspaceIdSessionsSessionIdRoute:
    WorkspacesWorkspaceIdSessionsSessionIdRoute,
  WorkspacesWorkspaceIdPeersPeerIdChatRoute:
    WorkspacesWorkspaceIdPeersPeerIdChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
