name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - uses: dtolnay/rust-toolchain@stable

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'OpenConcho ${{ github.ref_name }}'
          releaseBody: 'See assets below to download and install.'
          releaseDraft: false
          prerelease: false
